name: strata_ui
description: Reusable decoupled UI components and theme abstractions for the Strata framework.
version: 0.1.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.13.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^4.0.0
  carousel_slider: ^5.1.1
  equatable: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  get_it: ^9.0.5
  pinput: ^6.0.0
  readmore: ^3.0.0
  shimmer: ^4.0.0
  skeletonizer: ^3.0.0
  strata_core:
    path: ../strata_core
  strata_state:
    path: ../strata_state
  typed_form_fields: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
