name: strata_workspace
description: "Strata framework monorepo workspace."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.13.1 <4.0.0"

workspace:
  - strata
  - strata_core
  - strata_network
  - strata_state
  - strata_storage
  - strata_ui

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  melos: ^8.6.0

