name: strata_storage
description: Secure persistence infrastructure adapters and database setup helpers for Strata framework.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.13.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  fpdart: ^1.1.0
  get_it: ^9.0.5
  path_provider: ^2.1.5
  strata_core:
    path: ../strata_core

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.0
  plugin_platform_interface: ^2.1.0
